<a href="https://colab.research.google.com/github/Karishma-Kuria/ML-Pytorch-Tensor/blob/main/DL_Tensor_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Tensors using Pytorch**

Pytorch is popular DL library used for manupulating tensors.


In [88]:
# importing relevant libraries
import numpy as np
import torch

In [89]:
# 1 D tensor 
a = torch.ones(5)
print('1 D tensor: \n',a)

1 D tensor: 
 tensor([1., 1., 1., 1., 1.])


In [90]:
# 2 D tensor
b = torch.tensor([[1, 2, 3, 4], 
                  [3, 4 , 6, 7], [3, 4, 5, 7]])
print('2 D tensor: \n', b, '\n')

# prints the dimension of input tensor
print(b.size())

2 D tensor: 
 tensor([[1, 2, 3, 4],
        [3, 4, 6, 7],
        [3, 4, 5, 7]]) 

torch.Size([3, 4])


### **Accesing elements of 2 D tensors**

In [91]:
# creating a float tensor
b = torch.FloatTensor([[1.9, 2.0, 3.4, 4.0], 
                  [3.0, 4.4 , 6.4, 7.6], [3.2, 4.1, 5.1, 7.0]])
print(b, '\n')
# print the first row
print('The first row of tensor is: \n',b[0], '\n')

tensor([[1.9000, 2.0000, 3.4000, 4.0000],
        [3.0000, 4.4000, 6.4000, 7.6000],
        [3.2000, 4.1000, 5.1000, 7.0000]]) 

The first row of tensor is: 
 tensor([1.9000, 2.0000, 3.4000, 4.0000]) 



### **Various Datatypes of tensor.**

In [92]:
from torch._C import dtype
double_tensor = torch.ones(12,4, dtype= torch.double)
short_tensor = torch.tensor([[1,3], [2,4]], dtype= torch.short)
print('Double datatype tensor \n', double_tensor, '\n')
print('Short datatype tensor \n', short_tensor, '\n')

Double datatype tensor 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64) 

Short datatype tensor 
 tensor([[1, 3],
        [2, 4]], dtype=torch.int16) 



In [93]:
# casting the output of the tensor using the right cast 
double_tensor_val = torch.ones(12,4).double()
short_tensor_val = torch.ones(10,2).short()
print('Double Tensor',double_tensor_val, '\n')
print('Short datatype tensor',short_tensor_val)

Double Tensor tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64) 

Short datatype tensor tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)


### **Tensor Storage**

In [94]:
# checking the storage for the above tensor
print('Storage of the tensor \n',b.storage(),'\n')
# print storage of second row
print('Storage of the second row of tensor \n',b[1].storage())

Storage of the tensor 
  1.899999976158142
 2.0
 3.4000000953674316
 4.0
 3.0
 4.400000095367432
 6.400000095367432
 7.599999904632568
 3.200000047683716
 4.099999904632568
 5.099999904632568
 7.0
[torch.FloatStorage of size 12] 

Storage of the second row of tensor 
  1.899999976158142
 2.0
 3.4000000953674316
 4.0
 3.0
 4.400000095367432
 6.400000095367432
 7.599999904632568
 3.200000047683716
 4.099999904632568
 5.099999904632568
 7.0
[torch.FloatStorage of size 12]


### **Subtensor**: It has one less dimension while it indexes the same storage as the original tensor. If the subtensor is changed it has effect on the main tensor also.

In [95]:
second_tensor = b[1]
second_tensor[0] = 10.2
print('Parent tensor \n', b)

Parent tensor 
 tensor([[ 1.9000,  2.0000,  3.4000,  4.0000],
        [10.2000,  4.4000,  6.4000,  7.6000],
        [ 3.2000,  4.1000,  5.1000,  7.0000]])


As seen in the above output the value is changed of the first element of row 2.

### **Cloning tensor**

In [96]:
new_tensor = b[1].clone()
new_tensor[0] = 9.0
print('Parent tensor \n', b)
print('New tensor with changes value \n', new_tensor)

Parent tensor 
 tensor([[ 1.9000,  2.0000,  3.4000,  4.0000],
        [10.2000,  4.4000,  6.4000,  7.6000],
        [ 3.2000,  4.1000,  5.1000,  7.0000]])
New tensor with changes value 
 tensor([9.0000, 4.4000, 6.4000, 7.6000])


## **Broadcasting**

If the number of elements in the 2 arrays is not same, operations on these 2 arrays is still possible using broadcasting.
The smaller array is made similar to the bigger array so that the operations are successful.

In [97]:
# performing addition on different shaped arrays to see the effect of broadcasting
a = torch.empty(4,1,4,1)
b = torch.empty( 2,1,1)
(a+b).size()

torch.Size([4, 2, 4, 1])

### **Outer product with Broadcasting**

In [98]:
# doing the outer addition operation in 1 D array
a = np.array([1,2,3,4])
b = np.array([4,5,6])
a[:, np.newaxis] + b

array([[ 5,  6,  7],
       [ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10]])

In the above operation the **newaxis** adds a new axis into a array making it 4X1 array and combining it with b which is has size (3,) to make 4X3 resultant array.

### **Mathematical Operations on Tensor**

In [99]:
# initialize tensors
a = torch.tensor([[1,12,3],
                    [4,15,6],
                    [6,17,8]])
b = torch.tensor([[10,20,30],
                    [40,50,60],
                    [60,70,80]])
print(a,'\n')
print(b)

tensor([[ 1, 12,  3],
        [ 4, 15,  6],
        [ 6, 17,  8]]) 

tensor([[10, 20, 30],
        [40, 50, 60],
        [60, 70, 80]])


In [100]:
# addition
print('The resultant matrix after addition is: \n',torch.add(a,b))

The resultant matrix after addition is: 
 tensor([[11, 32, 33],
        [44, 65, 66],
        [66, 87, 88]])


In [101]:
# substraction
print('The resultant matrix after substraction is: \n',torch.sub(a,b))

The resultant matrix after substraction is: 
 tensor([[ -9,  -8, -27],
        [-36, -35, -54],
        [-54, -53, -72]])


In [102]:
# multiplication
# perform non- element wise matrix multiplication.
x = torch.mm(a, b)
# using @ operator performs the same operation as torch.mm
y = a@b
print(x, '\n')
print(y)

tensor([[ 670,  830,  990],
        [1000, 1250, 1500],
        [1220, 1530, 1840]]) 

tensor([[ 670,  830,  990],
        [1000, 1250, 1500],
        [1220, 1530, 1840]])


***torch.mm*** is used to perform matrix multiplication of any two input arrays which is not element wise.

In [103]:
# perfoming element wise multiplication
# all of these 3 approaches perform the same operation
x1 = torch.mul(a, b)
y1 = a * b
z1 = a.mul(b)
print(x1,'\n')
print(y1,'\n')
print(z1,'\n')

tensor([[  10,  240,   90],
        [ 160,  750,  360],
        [ 360, 1190,  640]]) 

tensor([[  10,  240,   90],
        [ 160,  750,  360],
        [ 360, 1190,  640]]) 

tensor([[  10,  240,   90],
        [ 160,  750,  360],
        [ 360, 1190,  640]]) 



In [104]:
# division
print('The resultant matrix after division is: \n',torch.div(a,b))

The resultant matrix after division is: 
 tensor([[0.1000, 0.6000, 0.1000],
        [0.1000, 0.3000, 0.1000],
        [0.1000, 0.2429, 0.1000]])


In [105]:
# inverse
# torch.inverse provides the inverse of the input matrix
a = torch.rand(7, 7)
print(a,'\n')
b = torch.inverse(a)
print(b,'\n')
print(a@b)

tensor([[0.4094, 0.1481, 0.2686, 0.0541, 0.6161, 0.6357, 0.6726],
        [0.6953, 0.8316, 0.2268, 0.2799, 0.8457, 0.8619, 0.8963],
        [0.0084, 0.0381, 0.9939, 0.3108, 0.8241, 0.7824, 0.3628],
        [0.9517, 0.1386, 0.4040, 0.5678, 0.2655, 0.5043, 0.5175],
        [0.7165, 0.0424, 0.3139, 0.8760, 0.4802, 0.6547, 0.7408],
        [0.7599, 0.0080, 0.1407, 0.2115, 0.4494, 0.3176, 0.7438],
        [0.6228, 0.7439, 0.0093, 0.5205, 0.3151, 0.6263, 0.5172]]) 

tensor([[ -0.1730,  10.6006,  -4.8955,   6.8608,   4.0334, -10.0051, -12.9653],
        [ -1.6954,  -5.4178,   3.2083,  -3.4025,  -3.6801,   6.7266,   8.3450],
        [ -1.1170, -13.5888,   7.0618,  -6.1348,  -7.2826,  14.0176,  16.4583],
        [ -1.8562,   2.0833,  -0.5099,   0.1104,   2.2922,  -1.5046,  -2.0683],
        [ -2.4428,  24.2866,  -9.3601,  10.4444,  10.9133, -20.7911, -28.5275],
        [  4.6087,   2.3560,  -2.6309,   3.0900,   1.9911,  -7.0542,  -4.0297],
        [  0.4426, -24.4741,  10.5548, -13.4737, -10.79

In [106]:
# concatenation

# concatenating 2 tensors vertically
c = torch.cat((a,b))
print('First Tensor: \n', a, '\n')
print('Second Tensor: \n', b, '\n')
print('Concatenated Tensor: \n', c, '\n')

First Tensor: 
 tensor([[0.4094, 0.1481, 0.2686, 0.0541, 0.6161, 0.6357, 0.6726],
        [0.6953, 0.8316, 0.2268, 0.2799, 0.8457, 0.8619, 0.8963],
        [0.0084, 0.0381, 0.9939, 0.3108, 0.8241, 0.7824, 0.3628],
        [0.9517, 0.1386, 0.4040, 0.5678, 0.2655, 0.5043, 0.5175],
        [0.7165, 0.0424, 0.3139, 0.8760, 0.4802, 0.6547, 0.7408],
        [0.7599, 0.0080, 0.1407, 0.2115, 0.4494, 0.3176, 0.7438],
        [0.6228, 0.7439, 0.0093, 0.5205, 0.3151, 0.6263, 0.5172]]) 

Second Tensor: 
 tensor([[ -0.1730,  10.6006,  -4.8955,   6.8608,   4.0334, -10.0051, -12.9653],
        [ -1.6954,  -5.4178,   3.2083,  -3.4025,  -3.6801,   6.7266,   8.3450],
        [ -1.1170, -13.5888,   7.0618,  -6.1348,  -7.2826,  14.0176,  16.4583],
        [ -1.8562,   2.0833,  -0.5099,   0.1104,   2.2922,  -1.5046,  -2.0683],
        [ -2.4428,  24.2866,  -9.3601,  10.4444,  10.9133, -20.7911, -28.5275],
        [  4.6087,   2.3560,  -2.6309,   3.0900,   1.9911,  -7.0542,  -4.0297],
        [  0.4426, -24

In [107]:
# concatenating 2 tensors horizontally
c = torch.cat((a,b), dim = 1)
print('Concatenated Tensor: \n', c, '\n')

Concatenated Tensor: 
 tensor([[ 4.0945e-01,  1.4807e-01,  2.6860e-01,  5.4088e-02,  6.1610e-01,
          6.3567e-01,  6.7261e-01, -1.7298e-01,  1.0601e+01, -4.8955e+00,
          6.8608e+00,  4.0334e+00, -1.0005e+01, -1.2965e+01],
        [ 6.9533e-01,  8.3159e-01,  2.2675e-01,  2.7993e-01,  8.4567e-01,
          8.6189e-01,  8.9631e-01, -1.6954e+00, -5.4178e+00,  3.2083e+00,
         -3.4025e+00, -3.6801e+00,  6.7266e+00,  8.3450e+00],
        [ 8.3898e-03,  3.8083e-02,  9.9395e-01,  3.1082e-01,  8.2405e-01,
          7.8235e-01,  3.6284e-01, -1.1170e+00, -1.3589e+01,  7.0618e+00,
         -6.1348e+00, -7.2826e+00,  1.4018e+01,  1.6458e+01],
        [ 9.5170e-01,  1.3859e-01,  4.0398e-01,  5.6775e-01,  2.6546e-01,
          5.0429e-01,  5.1753e-01, -1.8562e+00,  2.0833e+00, -5.0985e-01,
          1.1035e-01,  2.2922e+00, -1.5046e+00, -2.0683e+00],
        [ 7.1648e-01,  4.2406e-02,  3.1386e-01,  8.7596e-01,  4.8017e-01,
          6.5474e-01,  7.4076e-01, -2.4428e+00,  2.4287e+01, -9

By providing the ***dim*** parameter to 1, two tensors can be concatenated horizontally. We can perform this operation with number of tensors but we just have to make sure that the sizes of the tensors in the direction of the concatenation should be equal. 

## **Einsum Operations**

### **Outer Product**

In [108]:
a = torch.randn(7)
b = torch.randn(8)
outer_prod = torch.einsum('i,j->ij', a,b)
print('The outer product of a & b is:\n', outer_prod)

The outer product of a & b is:
 tensor([[-0.4836, -1.4250, -0.5651,  0.3457,  0.3690, -1.3707, -0.1158, -1.5470],
        [-0.3203, -0.9437, -0.3743,  0.2290,  0.2444, -0.9078, -0.0767, -1.0246],
        [-0.4696, -1.3836, -0.5487,  0.3357,  0.3583, -1.3308, -0.1124, -1.5021],
        [ 0.0229,  0.0676,  0.0268, -0.0164, -0.0175,  0.0650,  0.0055,  0.0734],
        [-0.0816, -0.2404, -0.0953,  0.0583,  0.0623, -0.2313, -0.0195, -0.2610],
        [-0.1350, -0.3976, -0.1577,  0.0965,  0.1030, -0.3825, -0.0323, -0.4317],
        [ 0.1202,  0.3540,  0.1404, -0.0859, -0.0917,  0.3405,  0.0288,  0.3844]])


### **Diagonal**

In [109]:
a = torch.randn(4,4)
# diagonal
diag = torch.einsum('ii->i', a)
print('Original matrix: \n', a, '\n')
print('Diagonal values: \n', diag)

Original matrix: 
 tensor([[ 0.9538,  0.2452,  0.8444,  0.8822],
        [-1.5615, -0.8985,  0.6918, -0.6780],
        [-1.0887, -1.3025,  0.7164,  0.5602],
        [ 0.5513, -1.0012,  0.5408, -0.0391]]) 

Diagonal values: 
 tensor([ 0.9538, -0.8985,  0.7164, -0.0391])


### **Batch Diagonal**

In [110]:
a = torch.randn(4,2,2)
diag = torch.einsum('...ii->...i', a)
print('Original matrix: \n', a, '\n')
print('Diagonal values: \n', diag)

Original matrix: 
 tensor([[[ 0.4518, -0.3787],
         [-0.1293,  0.3824]],

        [[-0.6235, -1.2724],
         [-0.8765,  0.4022]],

        [[ 0.2230,  1.4326],
         [ 1.3452, -0.5901]],

        [[-1.4139, -0.7924],
         [ 0.1980, -0.0091]]]) 

Diagonal values: 
 tensor([[ 0.4518,  0.3824],
        [-0.6235,  0.4022],
        [ 0.2230, -0.5901],
        [-1.4139, -0.0091]])


### **Element wise Cube**

In [111]:
a = torch.tensor([[1,2,3],
                    [4,5,6],
                    [6,7,8]])
cube = torch.einsum('ij,ij,ij-> ij', a,a,a)
cube

tensor([[  1,   8,  27],
        [ 64, 125, 216],
        [216, 343, 512]])

### **Element wise multiplication**

In [112]:
a = torch.tensor([[1,2,3],
                    [4,5,6],
                    [6,7,8]])
b = torch.tensor([[11,12,3],
                    [40,10,6],
                    [6,7,8]])
torch.einsum('ij,ij-> ij', a,b)

tensor([[ 11,  24,   9],
        [160,  50,  36],
        [ 36,  49,  64]])

### **Matrix Transpose**

In [113]:
a = torch.tensor([[1,2,3],
                    [4,5,6],
                    [6,7,8]])
print('Original matrix \n', a,'\n')
print('Transposed matrix \n', torch.transpose(a, 1,0))

Original matrix 
 tensor([[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]]) 

Transposed matrix 
 tensor([[1, 4, 6],
        [2, 5, 7],
        [3, 6, 8]])


### **Sum of main diagonal element**

In [114]:
a = torch.tensor([[1,2,3],
                    [4,5,6],
                    [6,7,8]])
torch.einsum('ii->', a)

tensor(14)

### **Sum along axis 2**

In [115]:
a = torch.arange(2*4*3).reshape(2,4,3)
print(a)
torch.einsum('ijk->ij', a)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]]])


tensor([[ 3, 12, 21, 30],
        [39, 48, 57, 66]])

### **Batch Multiplication**

In [116]:
a = torch.arange(3*4*3).reshape(3,4,3)
b = torch.arange(3*3*4).reshape(3,3,4)
torch.einsum('bij,bjk->bik', a,b)

tensor([[[  20,   23,   26,   29],
         [  56,   68,   80,   92],
         [  92,  113,  134,  155],
         [ 128,  158,  188,  218]],

        [[ 632,  671,  710,  749],
         [ 776,  824,  872,  920],
         [ 920,  977, 1034, 1091],
         [1064, 1130, 1196, 1262]],

        [[2108, 2183, 2258, 2333],
         [2360, 2444, 2528, 2612],
         [2612, 2705, 2798, 2891],
         [2864, 2966, 3068, 3170]]])