<a href="https://colab.research.google.com/github/Karishma-Kuria/ML-Pytorch-Tensor/blob/main/DL_Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Tensors**

Tensors are the data structure used in machine learning and are the basics which needs to be mastered by the engineers.
Tensors are the containers of data and can store data in various forms such as int, float, string etc. Tensors are immutable similar to number and strings in python, that means these cannot be updated.

In [118]:
# import relevant libraries
import tensorflow as tf
import numpy as np

We can use ***tf.dtypes.DType()*** for checking various default datatypes supported by tensor. DType is also used to specify the datatype of the output variable.

Creating basic tensors with various ranks.

This is a scaler or rank-0 tensor created for a constant. This tensor has no axes and has single value. 

In [119]:
# This will be an int32 tensor by default; see "dtypes" below.
tensor_rank_0 = tf.constant(6.9)
print(tensor_rank_0)


tf.Tensor(6.9, shape=(), dtype=float32)


This is a vector or rank-1 tensor created for a list of values. This tensor has one axes. 

In [120]:
# this is an int32 tensor.
tensor_rank_1 = tf.constant([3, 6, 4])
print(tensor_rank_1)

tf.Tensor([3 6 4], shape=(3,), dtype=int32)


Below is a matrix or rank-2 tensor created for a lists of values. Matrix tensor has 2 axes. 

In [121]:
# If you want to be specific, you can set the dtype (see below) at creation time
tensor_rank_2 = tf.constant([[10, 12],
                             [13, 14],
                             [15, 16]], dtype=tf.float16)
print(tensor_rank_2)

tf.Tensor(
[[10. 12.]
 [13. 14.]
 [15. 16.]], shape=(3, 2), dtype=float16)


We can also have tensors with multiple axes.

In [123]:
# there can be any number of axes also called dimensions
tensor_rank_3 = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(tensor_rank_3)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


Some Vocabulary related to tensor Shapes:

1.   Rank: Number of tensor axes. ex- a scaler's rank is 0, vector's rank is 1 and matrix's rank is 2.
2.  Shape: length (number of elements) of each of the axes of a tensor.
3. Size: total number of items in the tensor.
4. Axis or Dimension: particular dimension of a tensor


In [124]:
tensor_rank_4 = tf.zeros([1, 2, 3, 4])
print(tensor_rank_4)

tf.Tensor(
[[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]], shape=(1, 2, 3, 4), dtype=float32)


In [125]:
print("Data Type of every element:", tensor_rank_4.dtype)

Data Type of every element: <dtype: 'float32'>


In [126]:
print("Rank: Number of axes:", tensor_rank_4.ndim)

Rank: Number of axes: 4


In [127]:
print("Shape of tensor:", tensor_rank_4.shape)

Shape of tensor: (1, 2, 3, 4)


In [128]:
print("Elements along axis 0 of tensor:", tensor_rank_4.shape[0]) 

Elements along axis 0 of tensor: 1


In [129]:
print("Total number of elements: ", tf.size(tensor_rank_4).numpy())

Total number of elements:  24


### **Converting tensor to Numpy array**

In [130]:
np.array(tensor_rank_3)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]], dtype=int32)

In [131]:
tensor_rank_3.numpy()

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]], dtype=int32)

## **Types of Tensors**

### Ragged Tensors

In this type of tensor the axis contains variable numbers of elements called "ragged". For ragged data *tf.ragged.RaggedTensor* is used.

In [132]:
ragged_list = [
    [10, 17, 2, 3],
    [4, 15],
    [16, 7, 18],
    [19]]

In [133]:
tensor_val = tf.ragged.constant(ragged_list)
print(tensor_val.shape)

(4, None)


In [134]:
print(tensor_val)

<tf.RaggedTensor [[10, 17, 2, 3], [4, 15], [16, 7, 18], [19]]>


### String Tensors

String tensor contains strings as the element of the tensor as shown below.

In [135]:
# three string tensors.
string_tensor_val = tf.constant(["Apple",
                                 "Pineapple",
                                 "Kiwi"])
# shape is (3,). The length of string is not included.
print(string_tensor_val)

tf.Tensor([b'Apple' b'Pineapple' b'Kiwi'], shape=(3,), dtype=string)


### Sparse tensors

There are times when the data is sparse. Tensor gives us the facility to create tensors for sparse data also using ***tf.sparse.SparseTensor***.

In [136]:
# the values are stored by index in a memory efficient manner
sparse_tensor_val = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[1, 2],
                                       dense_shape=[3, 4])
print(sparse_tensor_val, "\n")


SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 



We can also convert sparse tensor into dense tensor as shown below:

In [137]:
# convert sparse to dense
print(tf.sparse.to_dense(sparse_tensor_val))

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


### **Working with Indexes**

### **Single Axis Indexing**

In [138]:
'''
 tensorflow also have similar indexing as python where 
 1. 0 is the first index
 2. - indexing from end
 3. colon : used to provide range of indexes
 '''

tensor_rank_1 = tf.constant([10, 11, 1, 12, 13, 15, 8, 13, 21, 34])
print(tensor_rank_1.numpy())

[10 11  1 12 13 15  8 13 21 34]


In [139]:
print("All elements After 3:", tensor_rank_1[3:].numpy())
print("From 2 to the 6:", tensor_rank_1[2:7].numpy())
print("Every alternate item:", tensor_rank_1[::2].numpy())
print("Elements from end: Reversed:", tensor_rank_1[::-1].numpy())

All elements After 3: [12 13 15  8 13 21 34]
From 2 to the 6: [ 1 12 13 15  8]
Every alternate item: [10  1 13  8 21]
Elements from end: Reversed: [34 21 13  8 15 13 12  1 11 10]


### **Multi Axis Indexing**

In [141]:
print(tensor_rank_2.numpy())

[[10. 12.]
 [13. 14.]
 [15. 16.]]


In [142]:
# print a single value from a 2 rank tensor
print(tensor_rank_2[0, 1].numpy())

12.0


In [143]:
# get row and column tensors
print("Third row:", tensor_rank_2[2, :].numpy())

Third row: [15. 16.]


In [144]:
print("Last row:", tensor_rank_2[-1, :].numpy())

Last row: [15. 16.]


In [145]:
print("First column:", tensor_rank_2[:, 0].numpy())

First column: [10. 13. 15.]


### **Manipulating Shapes**

In [146]:
# shape returns length (number of elements) of each of the axes of a tensor
y = tf.constant([[11], [12], [13], [10], [22], [23]])
print(y.shape)

(6, 1)


In [147]:
# convert y to Python list
print(y.shape.as_list())

[6, 1]


### Reshaping tensor into new shape.

In [148]:
reshaped_tensor = tf.reshape(y, [1, 6])
print(y.shape)
print(reshaped_tensor.shape)

(6, 1)
(1, 6)


In [149]:
# flattening tensor by passing -1 in 'shape' argument.
print(tf.reshape(tensor_rank_3, [-1]))

tf.Tensor(
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29], shape=(30,), dtype=int32)


Reshaping works for any new shape which has the same number of total elements, but if we don't respect the order of axes then it won't do well.

In [150]:
print(tf.reshape(tensor_rank_3, [3*2, 5]), "\n")
print(tf.reshape(tensor_rank_3, [3, -1]))

tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32) 

tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]], shape=(3, 10), dtype=int32)


### **Broadcasting and Maths Operations in tensors**

When we run combined operations on smaller and larger tensors then smaller tensors are "stretched" automatically to fit larger tensors this is called **Broadcasting**.

In [152]:
x_val = tf.constant([11, 12])

y_val = tf.constant(22)
z_val = tf.constant([22, 32])

In [153]:
# multiplying constant value with tensor
print(tf.multiply(x_val, 2))

tf.Tensor([22 24], shape=(2,), dtype=int32)


In [154]:
# multiplication of tensors
print(x_val * y_val)
print(x_val * z_val)

tf.Tensor([242 264], shape=(2,), dtype=int32)
tf.Tensor([242 384], shape=(2,), dtype=int32)


All the above calculations are same operations. Most of the time the broadcasting operation is both time and space efficient.

In [156]:
# these are the same computations
a = tf.reshape(x_val,[2,1])
b = tf.range(1, 6)
print(a, "\n")
print(b, "\n")
print(tf.multiply(a, b))

tf.Tensor(
[[11]
 [12]], shape=(2, 1), dtype=int32) 

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32) 

tf.Tensor(
[[11 22 33 44 55]
 [12 24 36 48 60]], shape=(2, 5), dtype=int32)


In the above operation a 2X1 matrix is multiplies with a 1X5 matrix to get a 2X5 matrix. 

### **Add operation in tensors.**

In [157]:
x = tf.constant([[11, 12],
                 [13, 14]])
y = tf.constant([[10, 11],
                 [12, 11]])
print(x, "\n") 
print(y, "\n") 

tf.Tensor(
[[11 12]
 [13 14]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[10 11]
 [12 11]], shape=(2, 2), dtype=int32) 



In [159]:
# add all the elements in the matix
print(tf.add(x, y), "\n")
# element wise addition
print(a + b, "\n") 

tf.Tensor(
[[21 23]
 [25 25]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[12 13 14 15 16]
 [13 14 15 16 17]], shape=(2, 5), dtype=int32) 



In [160]:
# multiply tensors
print(tf.multiply(x, y), "\n")

# element wise multiplication
print(x * y, "\n") 

tf.Tensor(
[[110 132]
 [156 154]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[110 132]
 [156 154]], shape=(2, 2), dtype=int32) 



In [161]:
# matmul can also be used for doing matrix multiplications
print(tf.matmul(x, y), "\n")
print(x @ y, "\n")

tf.Tensor(
[[254 253]
 [298 297]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[254 253]
 [298 297]], shape=(2, 2), dtype=int32) 



Tensors can be used to perform all kind of operations.

In [162]:
z = tf.constant([[4.1, 2.0], [10.02, 12.0]])

# find the largest value using 'tf.reduce_max()'
print('The largest value is:',tf.reduce_max(z), "\n")

# find the index of the largest value using 'tf.argmax()
print('Index of the largest value is:',tf.argmax(z),  "\n")

# compute the softmax of the tensors using tf.nn.softmax()
print(tf.nn.softmax(z),  "\n")

The largest value is: tf.Tensor(12.0, shape=(), dtype=float32) 

Index of the largest value is: tf.Tensor([1 1], shape=(2,), dtype=int64) 

tf.Tensor(
[[0.8909032  0.10909683]
 [0.12131889 0.8786811 ]], shape=(2, 2), dtype=float32) 



## **Einsum Operations**

In [163]:
a1 = tf.random.normal(shape = [3,2])
b1 = tf.random.normal(shape = [2,4])
print(a1, "\n")
print(b1)

tf.Tensor(
[[-1.052786   -0.9113805 ]
 [ 0.25496805  0.3239509 ]
 [ 0.20518586 -1.3156918 ]], shape=(3, 2), dtype=float32) 

tf.Tensor(
[[ 1.3554521   0.8975622   0.3596704  -0.61089057]
 [-0.07992326  0.40301463 -0.402025    0.45994073]], shape=(2, 4), dtype=float32)


### **Matrix multiplication**

In [165]:
mul = tf.einsum('ij,jk->ik', a1, b1)
print(mul, '\n')
print(mul.shape)

tf.Tensor(
[[-1.3541605  -1.3122406  -0.0122582   0.22395602]
 [ 0.31970575  0.35940662 -0.0385319  -0.00675938]
 [ 0.38327396 -0.34607595  0.6027403  -0.7304864 ]], shape=(3, 4), dtype=float32) 

(3, 4)


### **Dot Product**

In [166]:
a = tf.random.normal(shape = [3])
b = tf.random.normal(shape = [3])
dot_prod = tf.einsum('i,i->', a, b)
print(dot_prod, '\n')
print(dot_prod.shape)

tf.Tensor(0.75288546, shape=(), dtype=float32) 

()


### **Outer Product**

In [167]:
a = tf.random.normal(shape = [5])
b = tf.random.normal(shape = [4])
out_prod = tf.einsum('i,j-> ij', a, b)
print(out_prod, '\n')
print(out_prod.shape)

tf.Tensor(
[[-0.01345732  0.05288452  0.05951952  0.01899544]
 [ 0.10287452 -0.40427592 -0.45499727 -0.14521074]
 [-0.01027772  0.04038935  0.04545668  0.01450734]
 [-0.17406808  0.68405217  0.7698748   0.2457028 ]
 [ 0.1645474  -0.6466378  -0.7277664  -0.23226404]], shape=(5, 4), dtype=float32) 

(5, 4)


### **Transpose**

In [168]:
m = tf.ones(2,3)
e = tf.einsum('ij->ji', a1)
print(e.shape,'\n')
print(e)

(2, 3) 

tf.Tensor(
[[-1.052786    0.25496805  0.20518586]
 [-0.9113805   0.3239509  -1.3156918 ]], shape=(2, 3), dtype=float32)


### **Batch Matrix Multiplication**

In [169]:
a = tf.random.normal(shape=[6,5,3])
b = tf.random.normal(shape=[6,3,2])
e = tf.einsum('bij,bjk->bik', a,b)
print(e, '\n')
print(e.shape)

tf.Tensor(
[[[ 6.57200336e-01 -4.41879416e+00]
  [ 2.30680466e+00 -4.67814636e+00]
  [-5.22905588e-01  2.47513604e+00]
  [-3.53503537e+00  3.10064507e+00]
  [-1.32635653e+00  1.57345510e+00]]

 [[-2.74938226e-01 -1.89755166e+00]
  [ 1.29515088e+00 -3.97637033e+00]
  [ 9.16740060e-01 -6.66563654e+00]
  [ 2.45351005e+00 -3.65077782e+00]
  [-4.23577815e-01  1.88260150e+00]]

 [[ 1.67252553e+00 -1.89516351e-01]
  [ 4.05011415e-01 -2.10173100e-01]
  [ 1.18393862e+00  5.60243661e-03]
  [-1.88161325e+00 -5.31072497e-01]
  [-1.62057400e+00  1.10433543e+00]]

 [[-4.48367536e-01 -1.25517344e+00]
  [-1.17792034e+00 -1.86958754e+00]
  [ 1.32323718e+00 -1.42347479e+00]
  [ 3.24234200e+00  3.28374171e+00]
  [ 5.79168022e-01  1.38724482e+00]]

 [[-9.59357738e-01 -2.51388264e+00]
  [ 7.07653239e-02  9.85795498e-01]
  [ 9.85617787e-02 -2.11068821e+00]
  [-4.07542735e-02 -1.24355994e-01]
  [-5.30135989e-01 -6.38867676e-01]]

 [[-1.14357257e+00 -9.64187801e-01]
  [-2.70027667e-01 -1.15373135e+00]
  [ 8.4

### **Diagonal**

In [170]:
a = tf.reshape(tf.range(9), [3,3])
diag = tf.einsum('ii-> i', a)
print(diag, '\n')
print(diag.shape)

tf.Tensor([0 4 8], shape=(3,), dtype=int32) 

(3,)


### **Trace**

In [172]:
# in this repeated indices are summed
trace = tf.einsum('ii', a)
assert trace == sum(diag)
print(trace, '\n')
print(trace.shape)

tf.Tensor(12, shape=(), dtype=int32) 

()
